### ISSUE TITLE
Build out initial Apollo server infrastructure

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmsp_backend_prototype#1]
- [x] Setup/install Apollo server
- [x] Add the DMP ID to the GraphQL schema
- [x] Add a resolver that fetches DMP ID records from the DynamoDB Table
- [x] Add a Dockerfile to run the system in the AWS cloud
- [x] Add an AWS CodeBuild `buildspec.yaml` file
- [x] Add a Dockerfile to run the system locally

**Comment by mariapraetzellis** [comment]
This is up and running. Brian will create additional issues for new work.
