### ISSUE TITLE
User updates needed for the profile page: Add language_id to the users table, and add a languages table, need updates to schema and resolvers to update user data

### ISSUE THREAD

**Issue by jupiter007** [CDLUC3/dmsp_backend_prototype#128]
Currently, the new profile page needs a way to save the user's language, but there is no field for that under the users table

Wireframe: https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=771-1054&t=LIKQ4JuadoMKIEAS-8&scaling=scale-down-width&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=736%3A1772&show-proto-sidebar=1&hotspot-hints=0&hide-ui=1

A graphql query to get the user data should also have the ability to grab the selection of languages available for our Language field drop-down.

Also, we need to add User mutation schemas and resolvers so that we can save the user's profile preferences.

Associated NextJS ticket to build profile page: https://github.com/CDLUC3/dmsp_frontend_prototype/issues/124

**Comment by briri** [comment]
Add all of the fields in the schema definition in #53 to the DB table and model.

Only add the ones needed by the UI to the schema and resolvers for now
