### ISSUE TITLE
Build out Lookup tables

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmsp_backend_prototype#15]
The system will need a few tables that contain canned values. These should reside in the RDS instance.

Build the table in RDS and the corresponding scaffolding (Model, Controller, Policy) for each of the following tables:

tags (contributors (2), costs (7), ethics (3), project_details (1), funding, research_outputs (8), data_preservation (5), security_privacy(4), quality_assurance (6)) This table should include a 'default_order' refer to numbers listed here.
research_output_types (use the values the DMPTool has defined)
research_domains (use the [WebOfScience values](https://images.webofknowledge.com/images/help/WOK/hs_research_domains.html))
Refer to the https://github.com/CDLUC3/dmsp_aws_prototype/issues/79 on the dmsp_aws_prototype repo.

Build RSpec tests for everything!

**Comment by bofstein** [comment]
Related to https://github.com/CDLUC3/dmsp_frontend_prototype/issues/70

**Comment by bofstein** [comment]
Closing for now, keeping for reference, but will create new tickets as these come up as needs in new system
