### ISSUE TITLE
Define data model for Templates

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmsp_backend_prototype#33]
Need to define the schema behind the initial Template builder [wireframes](https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Explain?node-id=69-345&t=N2jvNbe3g9eOxDc7-0&scaling=min-zoom&page-id=6%3A66&starting-point-node-id=69%3A345) along with any queries and mutations needed to interact with the data.

Also make note of any logic or questions that pop up

**Comment by briri** [comment]
related to [dmsp_frontend_prototype #70](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/70)

**Comment by briri** [comment]
## Schema

### Template
- **id** [Int!]
- **name** [String!]
- **visibility** [String!] (options: Public, Private) (default: Private)
- **created** [DateTime!] (default current timestamp)
- **modified** [DateTime!] (default current timestamp)

### Template Collaborators
- **templateId** [Int!]
- **email** [String!]
- **created** [DateTime!] (default current timestamp)
- **userId** [Int] (blank if the email did not match an existing user account)
- **invitedBy** [Int] Id of the user who invited

### PublishedTemplate
- **id** [String!] (logic to determine if major/minor and then dynamically assign e.g. change one question's text is minor)
- **templateId** [Int!] Id of the underlying template that is being published
- **active** [Boolean] (default true)
- **name** [String!]
- **visibility** [String!] (options: Public, Private) (default: Private)
- **comment** [String]
- **publishedBy** [Int!] The user id
- **created** [DateTime!] (default current timestamp)

## Queries
- Get the templates for the user's affiliation `myTemplates(): Promise<Template[]>`
- Get a specific template `template(templateId: number): Promise<Template>`
- Get the "best practice" templates `bestPracticeTemplates(): Promise< PublishedTemplate[]>`
- Search for templates `publishedTemplates(term: string): Promise< PublishedTemplate[]>`
- Get a specific template `publishedTemplate(templateId: number): Promise<Template>`
- Get the collaborators for a template `templateCollaborators(templateId: number): Promise<TemplateCollaborators[]>`

## Mutations
- Create a template `addTemplate(name: string): Promise<Template>`
- Create a template from another template `copyTemplate(templateId: number, name: string): Promise<Template>`
- Update a template `updateTemplate(templateId: number, name: string, visibility: string): Promise<Template>` (errors included)
- Archive a template `archiveTemplate(templateId: number): Promise<boolean>`
- Publish a template `publishTemplate(templateId: number, comment: string): Promise<PublishedTemplate>`
- Add a collaborator to a template `addTemplateCollaborator(email: string): Promise<boolean>` 
- Remove a collaborator from a template `removeTemplateCollaborator(email: string): Promise<boolean>`

## Other
- The `addTemplateCollaborator` mutation should send out an email invite to the address specified if they do not have an account
- When a user registers their account, a query should be run to look for any templates they may have been invited to collaborate on. If any are found, then update the `templateCollaborator` table with the new user's id
- The `copyTemplate` mutation will need to clone the current published version of the template excluding the following: Collaborators, visibility (use default instead)
- Publishing involves the following:
  - If it is the first time:
    - Create the PublishedTemplate record based off of the current Template 
    - Publish (create snapshots) of all Sections, Questions, etc.
  - Otherwise
    - Create a new PublishedTemplate record based off of the current Template
    - Determine what changed and calculate a version number (major.minor)
    - Publish (create snapshots) of all Sections, Questions, etc.
    - Set the prior PublishedTemplate to `active = false`
    - Save the new PublishedTemplate

**Comment by jupiter007** [comment]
@briri I just remembered that users can add "comments" when saving as a draft, so does the Template table need a "comments" field? 



![Image](https://github.com/user-attachments/assets/6b652c73-8734-46e2-b6d4-c2b533017b22)

**Comment by briri** [comment]
I guess it's a question of how and when we persist data from the frontend to the backend.

I'm assuming we will persist changes to the backend as the user adds/edits sections and questions on a template. 

I made some modifications to the definition above based on the work I've done this week. Hopefully it illustrates the approach I am taking currently.

Basically. When a user clicks 'Save draft' or 'Save and Publish' it will:
- Clone the existing template, sections, questions, etc.
- Place the cloned items into the VersionedTemplate, VersionedSection, VersionedQuestion tables
- increment the version number (I'm thinking we automate this somehow)
- If its being "published"
  - set the `active` flag to true 
  - deactivate the prior version
  - figure out who we need to notify (e.g. some admin who added an overlay/guidance to a question that has changed)
 - if it is a "draft"
  - leave the existing published version alone
  - maybe notify collaborators to ask them to review?
  - maybe notify other admins who might have an overlay/guidance so they have an opportunity to review before it gets published?

**Comment by jupiter007** [comment]
@briri do we need to add a "description" field to the Template table? I noticed that the cards include what looks like a description:


![Image](https://github.com/user-attachments/assets/0ae084eb-7632-48b7-b65d-b74eb6b6d328)

**Comment by briri** [comment]
good question. I was wondering about that when I looked at the template options and other pages. I think we want to allow for it. I will add it to the defintiion

**Comment by briri** [comment]
@jupiter007 @fraserclark @andrewebdev 
Here is the finalized schema (for now, we may need to make minor tweaks as we start building):

I've set things up so that: 
- `Template` is always the current state of the Template regardless of whether or not there is a Draft or Published version out there.   
  - Used when an admin is adding/editing a template
  - Used when an admin is presented with a list of templates that they own
- `VersionedTemplate` is a snapshot of the `Template` taken when the user publishes or saves a draft. 
  - Used when an admin is selecting a template to copy (when creating a new template based off of another)
  - Used when a researcher is selecting a template
  - Used in basically all other areas of the system 
- `TemplateCollaborator` are email addresses associated with a Template. If a `userId` is present, it means the collaborator has an account.

Here are the available GraphQL queries and mutations:
```
// TEMPLATE
// -------------------------
// Get the Templates that belong to the current user's affiliation (user must be an Admin)
templates: [Template]

// Get a specific Template (user must be an Admin) 
template(templateId: Int!): Template

// Create a new Template. Leave the 'copyFromTemplateId' blank to create a new template from scratch
addTemplate(name: String!, copyFromTemplateId: Int): Template

// Update a Template
updateTemplate(templateId: Int!, name: String!, visibility: Visibility!): Template

// Archive a Template (un-publishes any associated VersionedTemplates)
archiveTemplate(templateId: Int!): Boolean

// Publish the template or Save as Draft
createVersion(templateId: Int!, comment: String, versionType: VersionType): Template

// VERSIONED TEMPLATE
// -------------------------
// Get all of the VersionedTemplate for the specified Template (a.k. the Template history)
templateVersions(templateId: Int!): [VersionedTemplate]

// Search for VersionedTemplate whose name or owning Org's name contains the search term (published versions only)
publishedTemplates(term: String!): [VersionedTemplate]

// TEMPLATE COLLABORATOR
// -------------------------
// Get all of the Users that belong to another affiliation that can edit the Template
templateCollaborators(templateId: Int!): [TemplateCollaborator]

// Add a collaborator to a Template
addTemplateCollaborator(templateId: Int!, email: String!): TemplateCollaborator

// Remove a TemplateCollaborator from a Template
removeTemplateCollaborator(templateId: Int!, email: String!): Boolean
```

Most objects will have the following properties available. I am excluding them from the schema devs below to save space:
```
id: Int.                                     // The unique identifer for the Object
createdById: Int                    // The user who created the Object
created: DateTimeISO          // The timestamp when the Object was created
modifiedById: Int                  // The user who last modified the Object
modified: DateTimeISO       // The timestamp when the Object was last modifed 
errors: [String!]                    // Errors associated with the Object
```

Here are the object definitions:
```

// Template visibility
enum TemplateVisibility {
  PRIVATE      // Visible only to users of your institution
  PUBLIC       // Visible to all users
}

type Template {
  sourceTemplateId: Int              // The template that this one was derived/copied from
  name: String!                            // The name/title of the template
  description: String                   // A description of the purpose of the template
  owner: Affiliation                      // The affiliation that the template belongs to
  visibility: TemplateVisibility!    // The template's availability setting: Public is available to everyone, Private only your affiliation
  currentVersion: String             // The current published version
  isDirty: Boolean!                      // Whether or not the Template has had any changes since it was last published
  bestPractice: Boolean!           // Whether or not this Template is designated as a 'Best Practice' template

  collaborators: [TemplateCollaborator!]    // Users from different affiliations who have been invited to collaborate on this template
}

enum TemplateVersionType {
  DRAFT             // Draft - saved state for internal review
  PUBLISHED    // Published - saved state for use when creating DMPs
}

type VersionedTemplate {
  template: Template                                   // The template that this published version stems from
  version: String!                                          // The major.minor semantic version (e.g. v1 or v1.1)
  versionedBy: User                                     // The person who is publishing or saving as draft
  versionType: TemplateVersionType         // The type of version: Published or Draft (default: Draft)
  comment: String                                       // A comment/note the user enters when publishing the Template
  active: Boolean!                                        // Whether or not this is the version provided when users create a new DMP (default: false)

  // The following fields are snapshots of the Template data
  name: String!
  description: String
  owner: Affiliation
  visibility: TemplateVisibility!
  bestPractice: Boolean!
}

type TemplateCollaborator {
  template: Template      // The template the collaborator may edit
  email: String!                // The collaborator's email
  user: User                     // The collaborator (if they have an account)
  invitedBy: User            // The user who invited the collaborator
}
```
