### ISSUE TITLE
Review GraphQL security measures

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmsp_backend_prototype#35]
We need to review these common security vulnerabilities with GraphQL to make sure we are addressing them all:

https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html#dos-prevention

We will be setting up an AWS web application firewall (WAF) so we can hopefully manage some DDoS issues with it's rate limiting capabilities.

**Comment by andrewebdev** [comment]
That website is also good for tracking security for other technologies as well. I frequent websites like this often when I develop apps.

**Comment by bofstein** [comment]
Have created other tickets based on this
