### ISSUE TITLE
Add resolvers for organizations

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmsp_backend_prototype#37]

**Comment by briri** [comment]
Added  these as part of PR #50
- GraphQL Schema 
- Mocks a handful of mock records for testing
- Models `Affiliation` and `AffiliationSearch`
- Resolvers: `affiliations(search: string, funderOnly: boolean): Promise<AffiliationSearch[]>` and `affiliation(affiliationId) Promise<Affiliation>` to the
