### ISSUE TITLE
Create resolver for the new DyanmoDB Table

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmsp_backend_prototype#4]
We need to setup a resolver that will be used to access the DynamoDB table that will store the non-DMP ID parts of the system (e.g. Users, guidance groups, templates, etc.)

**Comment by briri** [comment]
Need to have this look instead at the new index table which has replaced OpenSearch for now

**Comment by bofstein** [comment]
Closing because we are using RDS for that data
