### ISSUE TITLE
Decide on strategy for Logout

### ISSUE THREAD

**Issue by jupiter007** [CDLUC3/dmsp_backend_prototype#43]
We should create a "/logout" endpoint in the backend. Even though the frontend will delete the token cookie on logout, the backend should probably have its own logout endpoint to invalidate the token and to audit logging.

One common way of invalidating tokens if to use "Blacklisting", where the token is added to a blacklist in the database or in-memory store like Redis. We can possibly use "isRevokedCallback" to implement token invalidation in a stateless manner.

**Comment by bofstein** [comment]
Start with figuring out what/if we need this here, and make separate ticket for implementation, front end already removes cookie but token may still be valid

**Comment by jupiter007** [comment]
After doing some research, we should be try the following when a user makes a request to the "/logout" endpoint:

Since the backend server is already using "express-jwt", we should add the use of that package's "isRevoked". An example of this would be:

```
const authMiddleware = expressjwt({
  algorithms: ['HS256'],
  credentialsRequired: false,
  secret: generalConfig.jwtSecret as string,
  isRevoked: isRevokedCallback,
});
```
When using it in our middleware, like `router.use('/graphql', authMiddleware);` express-jwt automatically runs the "isRevokedCallback" to see if the token is in the invalidated list.

The isRevokedCallback function would look something like this:

```
const isRevokedCallback = async (req: Request, token?: jwt.Jwt):
  Promise<boolean> => {
  if (token && token.payload && typeof token.payload === 'object') {
    const jti = (token.payload as any).jti;
    if (jti) {
      const result = await getAsync(jti);
      return result !== null;
    }
  }
  return false;
}
```

I think we can use **Redis** to store the list of invalidated tokens. instead of storing the tokens in the list, we can store a new property, like "jti" in the jwt token along with the other data. The data in this "jti" property could be the Datetime, like:

```
    const payload: JWTToken = {
      id: user.id,
      email: user.email,
      givenName: user.givenName,
      surName: user.surName,
      jti: new Date().getTime().toString(),
      role: user.role.toString() || UserRole.Researcher,
    }
```
At our "/logout" endpoint, we could have code that looked something like:

```
router.post('/logout', authMiddleware, (req: Request, res: Response) => {
  const authorizationHeader = req.headers.authorization;
  if (authorizationHeader) {
    const token = authorizationHeader.split(' ')[1];
    const decoded = jwt.decode(token) as jwt.JwtPayload;

    if (decoded && decoded.jti) {
      const jti = decoded.jti;
      const expiresIn = decoded.exp ? decoded.exp - Math.floor(Date.now() / 1000) : 0;

      invalidateToken(jti, expiresIn).then(() => {
        res.send('Logged out');
      }).catch(err => {
        res.status(500).send('Error logging out');
      });
    } else {
      res.status(400).send('Invalid token')
    }
  } else {
    res.status(400).send('No authorization header found')
  }
});
```
and the "**invalidateToken**" function would add the token to the redis list:

```
const invalidateToken = async (jti: string, expiresIn: number): Promise<void> => {
  try {
    await setAsync(jti, 'true', 'EX', 'expiresIn');
    console.log(`Token with jti ${jti} has been invalidated.`)
  } catch (err) {
    console.error('Error invalidating token: ', err);
  }
};
```

We have to figure out how to incorporate "redis" into the index.ts and router.ts files.
