### ISSUE TITLE
Define Schema for Sections

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmsp_backend_prototype#52]
We need to review the [wireframes](https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Explain?node-id=69-345&t=N2jvNbe3g9eOxDc7-0&scaling=min-zoom&page-id=6%3A66&starting-point-node-id=69%3A345) related to Template Sections and define the initial schema, queries and logic that the backend will need to provide.

Related to #33

**Comment by briri** [comment]
### Section
- **id** Int!
- **name** String!
- **introduction** String 
- **requirements** String
- **tags** Int[]
- **created** DateTime! (default current timestamp)
- **modified** DateTime! (default current timestamp)

### PublishedSection
A "published" section is essentially just a snapshot of a Section at a point in time that the parent Template was published. Published sections are immutable!

- **id** Int! 
- **publishedTemplateId** Int! (Id of the parent publishedTemplate)
- **sectionId** Int! (Id of the underlying Section that this is a snapshot of)
- **created** DateTime! (default current timestamp)

### Queries
- Get the sections for a template `sections(templateId: number): Promise<Section[] | PublishedSection[]>`
- Get a specific section `section(sectionId: number): Promise<Section | PublishedSection>`
- Get the "best practice" sections `bestPracticeSections(): Promise< PublishedSection[]>`
- Search for sections `publishedSections(term: string): Promise< PublishedSection[]>`

### Mutations
- Create a section `addSection(templateId: number, name: string): Promise<Section>`
- Create a section from another section `copySection(templateId: number, sectionId: number, name: string): Promise<Section>`
- Update a section `updateSection(sectionId: number, name: string): Promise<Section>` (errors included)
- Delete a section `removeSection(sectionId: number): Promise<boolean>`

### Other Logic

### Versioning
- Versioning occurs when the parent template is published. The Template's Sections are published automatically in the backend

**Comment by fraserclark** [comment]
@briri Depending on how you see the data being stored but "section display order" might be important when we return the sections for a template

**Comment by jupiter007** [comment]
That's a good point @fraserclark. Maybe we could store the order in a TemplateSections table, which we will probably need to map template ids to sections ids.

**Comment by jupiter007** [comment]
@briri for the section tags, would it make more sense to create a `SectionTags` table, where we include the **section id** and the **tag id** rather than having an **Int[]** array of tags in each section record?

**Comment by briri** [comment]
Good points all around. I have updated the definition above.
- added 'displayOrder' to the sections table
- added a 'tags' and 'sectionTags' table 

I don't think we want a TemplateSections join table. A template has sections, but sections do not have templates. When someone selects an existing section from the library to add to their template, we will clone the section and attach that new copy to the template. This allows them to be modified independently within each template.

**Comment by jupiter007** [comment]
Thanks @briri. Should I update the above documentation with "displayOrder" and remove "tags" from "Sections" above? Or should we keep the final schema documentation in another location?

Also, Just to double check - a section is unique to just one template and cannot be shared across multiple templates?

**Comment by jupiter007** [comment]
@briri are we excluding "Section guidance" field? I can't remember. The wireframe includes it (see below), so if we need it we should add a "guidance" field to "Section" above.



![Image](https://github.com/user-attachments/assets/c4089db2-5f90-40db-9c07-5a6ccdf71151)

**Comment by jupiter007** [comment]
@briri I see what you are saying. So when a user selects an existing section for a new template, do we create a separate section id based off of the info from the existing template?

**Comment by fraserclark** [comment]
@briri @jupiter007 

I have always assumed the previously created sections are "locked in time" - a clone at the time of creation - zero linking or push/pulling of content. 

This applies to the DMP best practice sections too, they are only a starter kit, once you have selected the section, you have full ownership of it.

So, in your example where you add a new question to Roles and Responsibilities for template #3, you would need to back and update template #1 and template #2 with your new question.

However, it does bring up an interesting thought, which was never fully decided/thought through.

If you have 3 templates, you might have 3 "Roles and Responsibilities" in your "previously created sections" listed and it is hard to determine which one belongs to which previously created template.

I'd be reluctant in this "phase" of work to allow them to manage their "library of previous created sections” as it's a nice-to-have and we have more important things to work on.

I’d suggest we just add some text to suggest the "template" it is 'associated' with

**Comment by briri** [comment]
Yes 💯 we can just include the title to help them select the correct section from the library.

@jupiter007 yes, we would have a new id for the "copied" section. The MySQL DB uses an auto-increment number, so it will handle id assignment.

I think it makes sense to let the backend handle tasks like copying/cloning a section/template/question. We could have a GraphQL mutation called `cloneSection(newTemplateId: number, sectionToCloneId: number, displayPosition: number): Section`
Then the backend would copy the original section, attach the new templateId to it, change the name to `Copy of ...`, set the created timestamp and the createdById from the JWT, etc. Then save it which would assign an id, and return it to the front end.
