### ISSUE TITLE
Define schema for Users

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmsp_backend_prototype#53]
We need to review the [wireframes](https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Explain?node-id=771-1054&t=PKk0pf2RKfCQqKPt-9&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=736%3A1772&show-proto-sidebar=1) related to User sign in, registration and profile editing and define the initial schema, queries and logic that the backend will need to provide.

**Comment by briri** [comment]
### User
- **id** Int!
- **role** String! (options: Researcher, Admin, SuperAdmin) (default: Researcher)
- **givenName** String!
- **surName** String!
- **affiliationId** String! (ref to Affiliation)
- **password** String! (encrypted)
- **orcid** String 
- **ssoId** String
- **accepted_terms** Boolean! (default: false)
- **last_sign_in** String (Date time stamp)
- **reset_password_token** String
- **reset_password_token_ttl** Int
- **language** String! (default: en-US)
- **notification_comment_added** Boolean! (default: true)
- **notification_feedback_complete** Boolean! (default: true)
- **notification_plan_shared** Boolean! (default: true)
- **notification_template_shared** Boolean! (default: true) (admin only)
- **notification_plan_visibility_change** Boolean! (default: true) 
- **locked** Boolean! (default: false) (a way to lock the account after too many failed login attempts)
- **active** Boolean! (default: true) (a way for an admin to deactivate the user account)
- **created** DateTime! (default current timestamp)
- **modified** DateTime! (default current timestamp)

### UserEmail
- **email** String! 
- **primary** Boolean! 
- **confirmed** Boolean! (default: false) 
- **invitation_token** String 
- **invitation_ttl** Int
- **confirmation_token** String 
- **confirmation_ttl** Int
- **created** DateTime! (default current timestamp)


### Queries
- Get the current user `me(): Promise<User>`
- Search for users (admin only) `users(): Promise<User[]>`
- Get a specific user by Id `userById(userId: number): Promise<User>`
- Get a specific user by Email `userByEmail(email: string): Promise<User>`

### Mutations
Sign in, Register, password reset, email confirmation and invitiation acceptance methods are handled outside of GraphQL by specific endpoints which interact with the Schema and dataSources and create access tokens.

- Invite a user to create an account `inviteUser(email: string): Promise<boolean>`
- Update a specific user `updateUser(userId: number, givenName: string, surName: string, affiliationId: string, orcid: string, language: string, [all the notification_ types): boolean: Promise<User>` (errors included)
- Add an email for a user `addUserEmail(userId: number, email: string, isPrimary: string = false): Promise<boolean>`
- Remove an email from a user `removeUserEmail(userId: number, email: string): Promise<boolean>`
- Lock a user account `lockUser(userId: number): Promise<boolean>`
- Unlock a user account `unlockUser(userId: number): Promise<boolean>`
- Deactivate a user account `deactivateUser(userId: number): Promise<boolean>`
- Activate a user account `activateUser(userId: number): Promise<boolean>`

### Other Logic

### Versioning
- Versioning occurs when the parent template is published. The Template's Sections are published automatically in the backend

**Comment by jupiter007** [comment]
Just a few comments:

User:
- Will we need any additional name fields (e.g., some countries have two last name fields)

UserEmail:
- Does this need to include the **userId** field in order to associate the email with the user?

Mutations:
- For the **updateUser** mutation, would we need another field for the scenario where we have no affiliation id yet when the user selects the checkbox "**I cannot find my institution in the list**".
- For **addUserEmail**, the wireframe does not have a way for users to specify whether that new email is primary, so do we need to include the `isPrimary` field in the mutation?
- I believe we will need an **updateEmail** mutation for when a user wants to change an email to be the primary email.

**Comment by briri** [comment]
Good catch on the missing 'userId' in the Email table definition. I also added a 'newAffiliation' field to the `updateUser` mutation as a way to pass the name when they click 'not in the list'. I made a note to add that to the `register` endpoint as well.

Yes, we can probably get a single GraphQL query to fetch all of the data for the profile page.

I thought the wireframe had a link that said 'primary' next to the alternate emails as a way to change the designation. If not, we should update the wireframes to allow for the user to change it. I added a `designatePrimaryUserEmail` mutation.

I'm not sure on adding an additional field for a secondary surname. I'm trying to think through the logic of how they get used and displayed in different situations. 
- displaying in the first - last format: "Jane Doe Smith"
- displaying in the last - first format "Doe Smith, Jane"
- How do hyphenated names work?
- How do names with prepositions like 'van' work?
- There are probably other scenarios I'm missing

Would it work to have a surname field that is large enough to accommodate multiple names?

**Comment by jupiter007** [comment]
Thanks @briri. The existing alternate emails do have an option to update those emails to "primary", but when a user adds a new email address, there is currently no option in the wireframe to specify that is is primary. I was assuming that the "addUserEmail" mutation would be for that field, and not updating the existing emails.

<img width="707" alt="image" src="https://github.com/user-attachments/assets/c762021c-3c7e-4ba9-b599-7ee4e58a2ee0">

**Comment by jupiter007** [comment]
Lets run the name fields by Becky today to see if she has any ideas for how to handle that. Maybe we don't need it, but I checked our visitors on Matomo yesterday, and the second country listed was Brazil:

<img width="723" alt="image" src="https://github.com/user-attachments/assets/94cfc9b0-86c3-4ad9-98be-e9f8b01232c4">

**Comment by jupiter007** [comment]
Would it be possible to detect the user's country and show an extra last name field?

**Comment by briri** [comment]
🤷‍♂ I guess. Is that something easily detected on the frontend? I added a `secondarySurName` field to the definition
